# Generated by Django 2.1.1 on 2022-04-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=5000)),
                ('caller', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile', models.FileField(upload_to='media/profile')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User'),
        ),
        migrations.AddField(
            model_name='reply',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Story'),
        ),
        migrations.AddField(
            model_name='reply',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.User'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='client.User'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='client.User'),
        ),
    ]
