# Generated by Django 4.0.3 on 2022-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile',
            field=models.FileField(null=True, upload_to='media/profile'),
        ),
    ]
