# Generated by Django 4.0.3 on 2022-04-05 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_appuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
