# Generated by Django 4.0.3 on 2022-04-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_story_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='text',
            new_name='content',
        ),
    ]
