# Generated by Django 4.0.3 on 2022-04-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.appuser'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
