# Generated by Django 4.0.3 on 2022-04-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_reply_caller_alter_reply_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='caller',
            new_name='sender',
        ),
    ]
